#!/bin/bash

if [ -z "$1" ]; then
  echo "Give me a tag to build, please." >&2
  exit 1
fi

docker build -t discourse/elasticsearch_exporter:$1 .

if [ -n "$PUSH" ]; then
  docker push discourse/elasticsearch_exporter:$1
fi
